#include "FrameComposer.h"

#include "../capture/PointerShape.h"
#include "Rotation.h"

// Generated by FxCompile from the .hlsl files (see DeuxDisplayHost.vcxproj).
#include "CursorPS.h"
#include "CursorVS.h"

using Microsoft::WRL::ComPtr;

namespace dd::render
{

HRESULT FrameComposer::Initialize(ID3D11Device* device, UINT width, UINT height, UINT outWidth, UINT outHeight,
                                  uint16_t rotation)
{
    *this = FrameComposer{};
    m_device = device;
    m_device->GetImmediateContext(&m_context);
    m_width = width;
    m_height = height;
    m_outWidth = outWidth;
    m_outHeight = outHeight;
    m_rotation = rotation;

    D3D11_TEXTURE2D_DESC desc{};
    desc.Width = width;
    desc.Height = height;
    desc.MipLevels = 1;
    desc.ArraySize = 1;
    desc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
    desc.SampleDesc.Count = 1;
    desc.Usage = D3D11_USAGE_DEFAULT;
    desc.BindFlags = D3D11_BIND_RENDER_TARGET | D3D11_BIND_SHADER_RESOURCE;
    HRESULT hr = m_device->CreateTexture2D(&desc, nullptr, &m_compose);
    if (FAILED(hr))
    {
        return hr;
    }
    hr = m_device->CreateRenderTargetView(m_compose.Get(), nullptr, &m_composeRtv);
    if (FAILED(hr))
    {
        return hr;
    }

    hr = InitPointerPipeline();
    if (FAILED(hr))
    {
        return hr;
    }
    return InitVideoProcessor();
}

HRESULT FrameComposer::InitPointerPipeline()
{
    HRESULT hr = m_device->CreateVertexShader(g_CursorVS, sizeof(g_CursorVS), nullptr, &m_vs);
    if (FAILED(hr))
    {
        return hr;
    }
    hr = m_device->CreatePixelShader(g_CursorPS, sizeof(g_CursorPS), nullptr, &m_ps);
    if (FAILED(hr))
    {
        return hr;
    }

    D3D11_BUFFER_DESC cb{};
    cb.ByteWidth = 32; // four float2 corners
    cb.Usage = D3D11_USAGE_DEFAULT;
    cb.BindFlags = D3D11_BIND_CONSTANT_BUFFER;
    hr = m_device->CreateBuffer(&cb, nullptr, &m_rectBuffer);
    if (FAILED(hr))
    {
        return hr;
    }

    D3D11_SAMPLER_DESC sampler{};
    sampler.Filter = D3D11_FILTER_MIN_MAG_MIP_POINT;
    sampler.AddressU = sampler.AddressV = sampler.AddressW = D3D11_TEXTURE_ADDRESS_CLAMP;
    sampler.MaxLOD = D3D11_FLOAT32_MAX;
    hr = m_device->CreateSamplerState(&sampler, &m_sampler);
    if (FAILED(hr))
    {
        return hr;
    }

    D3D11_BLEND_DESC blend{};
    auto& rt = blend.RenderTarget[0];
    rt.BlendEnable = TRUE;
    rt.SrcBlend = D3D11_BLEND_SRC_ALPHA;
    rt.DestBlend = D3D11_BLEND_INV_SRC_ALPHA;
    rt.BlendOp = D3D11_BLEND_OP_ADD;
    rt.SrcBlendAlpha = D3D11_BLEND_ZERO;
    rt.DestBlendAlpha = D3D11_BLEND_ONE;
    rt.BlendOpAlpha = D3D11_BLEND_OP_ADD;
    rt.RenderTargetWriteMask = D3D11_COLOR_WRITE_ENABLE_ALL;
    hr = m_device->CreateBlendState(&blend, &m_blend);
    if (FAILED(hr))
    {
        return hr;
    }

    D3D11_RASTERIZER_DESC raster{};
    raster.FillMode = D3D11_FILL_SOLID;
    raster.CullMode = D3D11_CULL_NONE;
    return m_device->CreateRasterizerState(&raster, &m_rasterizer);
}

HRESULT FrameComposer::InitVideoProcessor()
{
    HRESULT hr = m_device.As(&m_videoDevice);
    if (FAILED(hr))
    {
        return hr;
    }
    hr = m_context.As(&m_videoContext);
    if (FAILED(hr))
    {
        return hr;
    }

    D3D11_VIDEO_PROCESSOR_CONTENT_DESC content{};
    content.InputFrameFormat = D3D11_VIDEO_FRAME_FORMAT_PROGRESSIVE;
    content.InputWidth = m_width;
    content.InputHeight = m_height;
    content.OutputWidth = m_outWidth;
    content.OutputHeight = m_outHeight;
    content.InputFrameRate = content.OutputFrameRate = {60, 1};
    content.Usage = D3D11_VIDEO_USAGE_OPTIMAL_SPEED;
    hr = m_videoDevice->CreateVideoProcessorEnumerator(&content, &m_vpEnum);
    if (FAILED(hr))
    {
        return hr;
    }
    hr = m_videoDevice->CreateVideoProcessor(m_vpEnum.Get(), 0, &m_vp);
    if (FAILED(hr))
    {
        return hr;
    }

    D3D11_VIDEO_PROCESSOR_INPUT_VIEW_DESC inDesc{};
    inDesc.ViewDimension = D3D11_VPIV_DIMENSION_TEXTURE2D;
    hr = m_videoDevice->CreateVideoProcessorInputView(m_compose.Get(), m_vpEnum.Get(), &inDesc, &m_vpInput);
    if (FAILED(hr))
    {
        return hr;
    }

    D3D11_TEXTURE2D_DESC desc{};
    desc.Width = m_outWidth;
    desc.Height = m_outHeight;
    desc.MipLevels = 1;
    desc.ArraySize = 1;
    desc.Format = DXGI_FORMAT_NV12;
    desc.SampleDesc.Count = 1;
    desc.Usage = D3D11_USAGE_DEFAULT;
    desc.BindFlags = D3D11_BIND_RENDER_TARGET | D3D11_BIND_VIDEO_ENCODER;

    D3D11_VIDEO_PROCESSOR_OUTPUT_VIEW_DESC outDesc{};
    outDesc.ViewDimension = D3D11_VPOV_DIMENSION_TEXTURE2D;
    for (size_t i = 0; i < kRingSize; ++i)
    {
        hr = m_device->CreateTexture2D(&desc, nullptr, &m_nv12[i]);
        if (FAILED(hr))
        {
            // Some drivers reject BIND_VIDEO_ENCODER on NV12 render targets; it's only a hint.
            desc.BindFlags = D3D11_BIND_RENDER_TARGET;
            hr = m_device->CreateTexture2D(&desc, nullptr, &m_nv12[i]);
        }
        if (FAILED(hr))
        {
            return hr;
        }
        hr = m_videoDevice->CreateVideoProcessorOutputView(m_nv12[i].Get(), m_vpEnum.Get(), &outDesc, &m_vpOutput[i]);
        if (FAILED(hr))
        {
            return hr;
        }
    }

    // Full-range RGB in, BT.709 limited-range YCbCr out (what the encoder signals in the VUI).
    ComPtr<ID3D11VideoContext1> videoContext1;
    if (SUCCEEDED(m_videoContext.As(&videoContext1)))
    {
        videoContext1->VideoProcessorSetStreamColorSpace1(m_vp.Get(), 0, DXGI_COLOR_SPACE_RGB_FULL_G22_NONE_P709);
        videoContext1->VideoProcessorSetOutputColorSpace1(m_vp.Get(), DXGI_COLOR_SPACE_YCBCR_STUDIO_G22_LEFT_P709);
    }
    else
    {
        D3D11_VIDEO_PROCESSOR_COLOR_SPACE in{};
        in.RGB_Range = 0;
        m_videoContext->VideoProcessorSetStreamColorSpace(m_vp.Get(), 0, &in);
        D3D11_VIDEO_PROCESSOR_COLOR_SPACE out{};
        out.YCbCr_Matrix = 1;
        out.Nominal_Range = D3D11_VIDEO_PROCESSOR_NOMINAL_RANGE_16_235;
        m_videoContext->VideoProcessorSetOutputColorSpace(m_vp.Get(), &out);
    }
    m_videoContext->VideoProcessorSetStreamFrameFormat(m_vp.Get(), 0, D3D11_VIDEO_FRAME_FORMAT_PROGRESSIVE);
    m_videoContext->VideoProcessorSetStreamAutoProcessingMode(m_vp.Get(), 0, FALSE);

    // Scale the whole desktop into the whole output (a no-op when sizes match).
    const RECT src{0, 0, static_cast<LONG>(m_width), static_cast<LONG>(m_height)};
    const RECT dst{0, 0, static_cast<LONG>(m_outWidth), static_cast<LONG>(m_outHeight)};
    m_videoContext->VideoProcessorSetStreamSourceRect(m_vp.Get(), 0, TRUE, &src);
    m_videoContext->VideoProcessorSetStreamDestRect(m_vp.Get(), 0, TRUE, &dst);
    m_videoContext->VideoProcessorSetOutputTargetRect(m_vp.Get(), TRUE, &dst);
    return S_OK;
}

HRESULT FrameComposer::UpdatePointerTexture(const capture::PointerState& pointer)
{
    if (pointer.shapeVersion == m_pointerVersion && m_pointerSrv)
    {
        return S_OK;
    }
    m_pointerVersion = pointer.shapeVersion;
    m_pointerSrv.Reset();
    m_pointerTexture.Reset();

    const auto& info = pointer.shapeInfo;
    const auto img = capture::ConvertPointerShape(static_cast<capture::PointerType>(info.Type), info.Width,
                                                  info.Height, info.Pitch, pointer.shape);
    if (img.width == 0)
    {
        return S_OK;
    }

    D3D11_TEXTURE2D_DESC desc{};
    desc.Width = img.width;
    desc.Height = img.height;
    desc.MipLevels = 1;
    desc.ArraySize = 1;
    desc.Format = DXGI_FORMAT_B8G8R8A8_UNORM;
    desc.SampleDesc.Count = 1;
    desc.Usage = D3D11_USAGE_IMMUTABLE;
    desc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
    D3D11_SUBRESOURCE_DATA data{img.bgra.data(), img.width * 4, 0};
    HRESULT hr = m_device->CreateTexture2D(&desc, &data, &m_pointerTexture);
    if (FAILED(hr))
    {
        return hr;
    }
    m_pointerWidth = img.width;
    m_pointerHeight = img.height;
    return m_device->CreateShaderResourceView(m_pointerTexture.Get(), nullptr, &m_pointerSrv);
}

void FrameComposer::DrawPointer(const capture::PointerState& pointer)
{
    const float w = static_cast<float>(m_width);
    const float h = static_cast<float>(m_height);
    const float x = static_cast<float>(pointer.position.x);
    const float y = static_cast<float>(pointer.position.y);
    const float pw = static_cast<float>(m_pointerWidth);
    const float ph = static_cast<float>(m_pointerHeight);

    // The pointer is in desktop coordinates; place its corners in the (possibly rotated) scan-out
    // frame. Keeping each corner's texture coordinate fixed rotates the pointer image with it.
    const PointF desktopCorners[4] = {{x, y}, {x + pw, y}, {x, y + ph}, {x + pw, y + ph}};
    float corners[8] = {};
    for (int i = 0; i < 4; ++i)
    {
        const PointF s = DesktopToScanout(desktopCorners[i], w, h, m_rotation);
        corners[i * 2] = s.x / w * 2.0f - 1.0f;
        corners[i * 2 + 1] = 1.0f - s.y / h * 2.0f;
    }
    m_context->UpdateSubresource(m_rectBuffer.Get(), 0, nullptr, corners, 0, 0);

    D3D11_VIEWPORT viewport{0, 0, w, h, 0, 1};
    m_context->RSSetViewports(1, &viewport);
    m_context->RSSetState(m_rasterizer.Get());
    m_context->OMSetRenderTargets(1, m_composeRtv.GetAddressOf(), nullptr);
    m_context->OMSetBlendState(m_blend.Get(), nullptr, 0xFFFFFFFF);
    m_context->IASetInputLayout(nullptr);
    m_context->IASetPrimitiveTopology(D3D11_PRIMITIVE_TOPOLOGY_TRIANGLESTRIP);
    m_context->VSSetShader(m_vs.Get(), nullptr, 0);
    m_context->VSSetConstantBuffers(0, 1, m_rectBuffer.GetAddressOf());
    m_context->PSSetShader(m_ps.Get(), nullptr, 0);
    m_context->PSSetShaderResources(0, 1, m_pointerSrv.GetAddressOf());
    m_context->PSSetSamplers(0, 1, m_sampler.GetAddressOf());
    m_context->Draw(4, 0);

    ID3D11RenderTargetView* noRtv = nullptr;
    m_context->OMSetRenderTargets(1, &noRtv, nullptr);
}

HRESULT FrameComposer::Compose(ID3D11Texture2D* desktop, const capture::PointerState& pointer,
                               ID3D11Texture2D** nv12)
{
    m_context->CopyResource(m_compose.Get(), desktop);

    if (pointer.visible && !pointer.shape.empty())
    {
        HRESULT hr = UpdatePointerTexture(pointer);
        if (FAILED(hr))
        {
            return hr;
        }
        if (m_pointerSrv)
        {
            DrawPointer(pointer);
        }
    }

    return ConvertLast(nv12);
}

HRESULT FrameComposer::ConvertLast(ID3D11Texture2D** nv12)
{
    const size_t slot = m_next;
    m_next = (m_next + 1) % kRingSize;

    D3D11_VIDEO_PROCESSOR_STREAM stream{};
    stream.Enable = TRUE;
    stream.pInputSurface = m_vpInput.Get();
    HRESULT hr = m_videoContext->VideoProcessorBlt(m_vp.Get(), m_vpOutput[slot].Get(), 0, 1, &stream);
    if (FAILED(hr))
    {
        return hr;
    }
    // Kick the batched copy/convert to the GPU now instead of whenever D3D decides to.
    m_context->Flush();
    *nv12 = m_nv12[slot].Get();
    (*nv12)->AddRef();
    return S_OK;
}

} // namespace dd::render
