<#
.SYNOPSIS
  Regenerates the Android dock icons from Lucide.

.DESCRIPTION
  Downloads the pinned lucide-static version's SVGs from jsDelivr, converts each to an Android
  vector drawable (white 2 px stroke) in android/app/src/main/res/drawable/dock_*.xml, and
  rewrites android/THIRD_PARTY_NOTICES.md with Lucide's license.

  Builds don't run this: the generated files are committed, so builds stay offline and
  reproducible and every icon change shows up as a reviewable diff. Run it after changing
  -Version or the icon list below, then commit the result.
#>
[CmdletBinding()]
param(
    [string]$Version = '1.48.0'
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12

# Drawable name -> Lucide icon name (https://lucide.dev/icons).
$Icons = [ordered]@{
    dock_undo         = 'undo-2'
    dock_redo         = 'redo-2'
    dock_task_view    = 'layout-panel-left'
    dock_play         = 'play'
    dock_pause        = 'pause'
    dock_handle       = 'layout-grid'
    dock_close        = 'x'
    dock_volume       = 'volume-2'
    dock_volume_muted = 'volume-x'
}

$Root = Split-Path $PSScriptRoot -Parent
$Drawables = Join-Path $Root 'android\app\src\main\res\drawable'
$Notices = Join-Path $Root 'android\THIRD_PARTY_NOTICES.md'
$BaseUrl = "https://cdn.jsdelivr.net/npm/lucide-static@$Version"
$Inv = [Globalization.CultureInfo]::InvariantCulture

function Get-Text([string]$Url) {
    Write-Host "Downloading $Url"
    $response = Invoke-WebRequest -Uri $Url -UseBasicParsing
    # Content is a string for text/* but bytes for some types (e.g. image/svg+xml).
    if ($response.Content -is [byte[]]) { return [Text.Encoding]::UTF8.GetString($response.Content) }
    return [string]$response.Content
}

function Format-Number([double]$Value) { $Value.ToString('0.####', $Inv) }

function Get-Attributes([string]$Tag) {
    $attributes = @{}
    foreach ($m in [regex]::Matches($Tag, '([\w-]+)="([^"]*)"')) { $attributes[$m.Groups[1].Value] = $m.Groups[2].Value }
    return $attributes
}

function Get-Number($Attributes, [string]$Name, [double]$Default = 0) {
    if ($Attributes.ContainsKey($Name)) { return [double]::Parse($Attributes[$Name], $Inv) }
    return $Default
}

# Vector drawables only have <path>, so circles and rects become path data.
function ConvertTo-PathData([string]$Element, [string]$Tag) {
    $a = Get-Attributes $Tag
    switch ($Element) {
        'path' { return $a['d'] }
        'circle' {
            $cx = Get-Number $a 'cx'; $cy = Get-Number $a 'cy'; $r = Get-Number $a 'r'
            $rs = Format-Number $r
            return "M$(Format-Number ($cx - $r)),$(Format-Number $cy)" +
                "a$rs,$rs 0 1,0 $(Format-Number (2 * $r)),0" +
                "a$rs,$rs 0 1,0 $(Format-Number (-2 * $r)),0z"
        }
        'rect' {
            $x = Get-Number $a 'x'; $y = Get-Number $a 'y'
            $w = Get-Number $a 'width'; $h = Get-Number $a 'height'
            $r = Get-Number $a 'rx' (Get-Number $a 'ry')
            if ($r -eq 0) {
                return "M$(Format-Number $x),$(Format-Number $y)h$(Format-Number $w)v$(Format-Number $h)h$(Format-Number (-$w))z"
            }
            $rs = Format-Number $r
            $corner = "a$rs,$rs 0 0,1"
            return "M$(Format-Number ($x + $r)),$(Format-Number $y)h$(Format-Number ($w - 2 * $r))" +
                "$corner $rs,${rs}v$(Format-Number ($h - 2 * $r))" +
                "$corner -$rs,${rs}h$(Format-Number (-($w - 2 * $r)))" +
                "$corner -$rs,-${rs}v$(Format-Number (-($h - 2 * $r)))" +
                "$corner $rs,-${rs}z"
        }
        default { throw "Unsupported SVG element <$Element>" }
    }
}

$utf8 = New-Object Text.UTF8Encoding($false)
foreach ($entry in $Icons.GetEnumerator()) {
    $svg = Get-Text "$BaseUrl/icons/$($entry.Value).svg"
    $shapes = [regex]::Matches($svg, '<(path|circle|rect)\b([^>]*?)/?>')
    if ($shapes.Count -eq 0) { throw "No shapes in $($entry.Value).svg" }
    $paths = foreach ($shape in $shapes) {
        $data = ConvertTo-PathData $shape.Groups[1].Value $shape.Groups[2].Value
        @"
    <path
        android:pathData="$data"
        android:strokeColor="#FFFFFF"
        android:strokeWidth="2"
        android:strokeLineCap="round"
        android:strokeLineJoin="round" />

"@
    }
    $xml = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- Lucide icon "$($entry.Value)" (lucide-static $Version, ISC). Generated by scripts/update-dock-icons.ps1; see android/THIRD_PARTY_NOTICES.md. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="24dp"
    android:height="24dp"
    android:viewportWidth="24"
    android:viewportHeight="24">

"@ + ($paths -join '') + "</vector>`n"
    [IO.File]::WriteAllText((Join-Path $Drawables "$($entry.Key).xml"), $xml.Replace("`r`n", "`n"), $utf8)
}

$license = (Get-Text "$BaseUrl/LICENSE").Trim()
$names = ($Icons.Values | ForEach-Object { $_ }) -join ', '
$notice = @"
# Third-party notices (Android app)

The shortcut dock's icons (``app/src/main/res/drawable/dock_*.xml``) are converted from
[Lucide](https://lucide.dev) (``lucide-static`` $Version) by ``scripts/update-dock-icons.ps1``:
$names. Only the file format changed (SVG shapes to Android vector paths, white stroke).
Lucide's license follows.

``````
$license
``````

"@
[IO.File]::WriteAllText($Notices, $notice.Replace("`r`n", "`n"), $utf8)
Write-Host "Wrote $($Icons.Count) icons and $Notices"
